# Usa una imagen base oficial de Nginx
FROM nginx:alpine

# Copia los archivos estáticos de tu aplicación al directorio de Nginx
# Esto incluye index.html, y las carpetas css y js dentro de static
# NOTA: Durante el desarrollo, los volumes en docker-compose.yml sobrescribirán esto,
# pero es buena práctica para la construcción final de la imagen.
COPY index.html /usr/share/nginx/html/index.html
COPY static /usr/share/nginx/html/static

# Exponer el puerto 80, que es el puerto por defecto de Nginx
EXPOSE 80

# Comando para iniciar Nginx cuando el contenedor se ejecute
CMD ["nginx", "-g", "daemon off;"]