version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    environment:
      FLASK_APP: app.py
      FLASK_ENV: development
    command: flask run --host=0.0.0.0 --port=5000

  frontend:
    build: ./frontend # Esta línea es la que define el contexto de construcción
    ports:
      - "80:80"
    # ¡ELIMINA LAS LÍNEAS DE VOLUMES AQUÍ!
    # No debería haber:
    # - ./frontend/index.html:/usr/share/nginx/html/index.html
    # - ./frontend/static:/usr/share/nginx/html/static
    depends_on:
      - backend