name: CI - Mini Gestor de Tareas

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt

      - name: Verificar sintaxis del backend
        run: |
          python -m py_compile backend/app.py

      - name: Ejecutar pruebas
        run: |
          cd backend
          export PYTHONPATH=$PYTHONPATH:$(pwd)
          pytest tests

      - name: Construir imagen Docker
        run: |
          docker build -t gestor-tareas ./backend

